services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sync-store-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./.env:/var/www/html/.env
      - ./database:/var/www/html/database
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    command: php artisan serve --host=0.0.0.0 --port=8000
